compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
name = "pzzld-org-app"
workers_dev = true

[build]
command = "opennextjs-cloudflare build"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability.logs]
enabled = true

[vars]
NEXT_PUBLIC_SITE_URL = "https://app.pzzld.org"
NEXT_PUBLIC_SUPABASE_URL = "https://gilqgzjkzkmhbbcqidqb.supabase.co"
NEXT_TELEMETRY_DISABLED = 1
NODE_ENV = "production"
NODE_VERSION = 24

[[routes]]
custom_domain = true
pattern = "app.pzzld.org"
zone_id = "pzzld.org"
