/**
 * Created At: 2025.07.14:09:20:22
 * @author - @FL03
 * @file - types.ts
 */
import { cva, VariantProps } from "class-variance-authority";

/**
 * The `dashboardSectionVariants` define and initialize the variants for the dashboard section component using the `cva` method from the `class-variance-authority` package.
 */
export const dashboardSectionVariants = cva("flex flex-1 w-full gap-2 p-2", {
  defaultVariants: {
    flavor: "default",
    style: "default",
    variant: "default",
  },
  variants: {
   flavor: {
      default: "bg-background text-foreground border-muted",
      accent: "bg-accent text-accent-foreground border-accent/10",
      primary: "bg-primary text-primary-foreground border-primary/10",
      secondary: "bg-secondary text-secondary-foreground border-secondary/10",
      transparent: "bg-transparent text-foreground border-none",
    },
    style: {
      default: "border rounded-2xl shadow-inner drop-shadow-lg",
    },
    variant: {
      default: "flex-col h-full",
      horizontal: "flex-row flex-nowrap items-center",
    },
  },
});

/** The type of variant properties generated by the `class-variance-authority`package's `cva` function. */
export type DashboardSectionVariants = VariantProps<
  typeof dashboardSectionVariants
>;
